version: "2"

linters:
  # Default: standard
  default: standard
  #default: all

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gofumpt:
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
